title: Free me
description: >-
  I’m notStupid but I’m not the smartest Tool in the shed Sorry for being mean
  and I guess being lied to my whole life and having a fucked up last night now
  on you’re being treated like crap and lose my mind and doing stuff I don’t
  need to do so now I guess
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
